# Setup
title:               'Hop Infosec'
tagline:             ''
description:         'My Public notes while I navigate infosec and find my niche'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              HopScotch
  url:               https://twitter.com/0xHop
  email:             0xh0psc0tch@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
#google_analytics_id: #UA-XXXX-Y
